CC = gcc

CFLAGS = -Wall -Wextra -O0 -g3 -Isrc/sdl12 -Isrc
LDFLAGS = -lcurl -lSDL -lSDL_image -lSDL_ttf
OUTPUT = rule34curl

SOURCES = src/core.c src/SDL_gui.c src/sdl12/SDL_gui_lib.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS}
	
clean:
	rm *.o
	rm ${OUTPUT}
