CC = gcc

CFLAGS = -Wall -Wextra -Ofast -march=native -mtune=native
LDFLAGS = -lcurl -lSDL -lSDL_image -lSDL_ttf
OUTPUT = rule34curl

SOURCES = core.c SDL_gui.c SDL_gui_lib.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS}
	
clean:
	rm *.o
	rm ${OUTPUT}
