CC = gcc

CFLAGS = -Wall -Wextra -O0 -g3 -Isrc/sdl2 -Isrc
LDFLAGS = -lcurl -lSDL2 -lSDL2_image
OUTPUT = rule34curl

SOURCES = src/core.c src/SDL_gui.c src/sdl2/SDL_gui_lib.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS}
	
clean:
	rm *.o
	rm ${OUTPUT}
